eos-vm-oc-enable = 1
chain-state-db-size-mb = 200
verbose-http-errors = true
allowed-connection = any
p2p-max-nodes-per-host = 10

plugin = eosio::chain_api_plugin
plugin = eosio::chain_plugin
plugin = eosio::http_plugin
## Enable for producer node
plugin = eosio::net_plugin
plugin = eosio::db_size_api_plugin
## Enable for state history
plugin = eosio::chain_api_plugin
plugin = eosio::state_history_plugin

## More State History Config
state-history-dir = "state-history"
trace-history = true
chain-state-history = true
state-history-endpoint = *********:9090

disable-replay-opts = true
read-only-read-window-time-us = 165000
read-only-write-window-time-us = 50000
read-only-threads = 4

# stop processes when disk space is 98% 
# default is too low
resource-monitor-space-threshold = 98
# DONT VALIDATE HOSTS
# OK when behind nginx proxy or firewall blocks
http-validate-host = false